############# English navigation ##############

# main menu
[[main]]
name = "HOME"
url = "/"
weight = 1

[[main]]
name = "SERVICES"
url = "/services"
weight = 2

[[main]]
name = "BLOG"
url = "/blog"
weight = 3

[[main]]
name = "PROJECTS"
url = "https://github.com/kubasejdak-org"
weight = 4

[[main]]
name = "ABOUT ME"
url = "/about"
weight = 5

# footer menu
[[footer]]
name = "ABOUT ME"
url = "/about"
weight = 1

[[footer]]
name = "PRIVACY"
url = "/privacy"
weight = 2
